name: Trigger Ubuntu22.04 CI
run-name: Ubuntu22.04 - ${{ github.event.pull_request.title }}

on:
  pull_request_target:
    types:
      - labeled
    paths:
      - '.github/workflows/trigger-ubuntu-win-build.yml'
      - '.github/workflows/ubuntu*.yml'
      - 'helpers/GenerateResourcesAndImage.ps1'
      - 'images/ubuntu/**'

defaults:
  run:
    shell: pwsh

jobs:
  Ubuntu_2204:
    if: github.event.label.name == 'CI ubuntu-all' || github.event.label.name == 'CI ubuntu-2204'
    uses: ./.github/workflows/trigger-ubuntu-win-build.yml
    with:
      image_type: 'ubuntu2204'
    secrets: inherit
